---
- name: Gather distribution info
  hosts: [nodes]
  gather_facts: false
  pre_tasks:
  - name: gathering distribution
    tags: always
    setup:
      filter: "ansible_distribution*"
- name: initial network setup
  hosts: [nodes]
  gather_facts: false
  become: true
  roles: 
  - network_setup 
- name: Users on head node & register worker hosts
  hosts: [namenode, spark_edge] 
  gather_facts: false
  become: true
  roles: 
  - ssh2nodes 
- name: worker nodes users & passwordless ssh
  hosts: [nodes]
  gather_facts: false
  become: true
  roles: 
  - ssh2me 
- name: local user can impersonate users on remote hosts
  hosts: [localsshnodes]
  gather_facts: false
  become: true
  roles: 
  - sshAsUsers 
- name: if we are about to upgrade hadoop wze need to start the upgrade and unlink services
  hosts: namenode
  gather_facts: false
  become: true
  roles:
  - prepare_upgrade_namenode
- name: if we are about to upgrade hadoop we will stop name nodes and unmlink datanode service
  hosts: datanodes
  gather_facts: false
  become: true
  roles:
  - prepare_upgrade_datanode
- name: installing hadoop components
  hosts: nodes
  gather_facts: false
  become: true
  roles: 
  - hadoop_node 
  environment:
    TMPDIR: "{{ tmp_dir }}"
    HTTPS_PROXY: "http://{{ proxy_host }}:{{ proxy_port }}"
    HTTP_PROXY: "http://{{ proxy_host }}:{{ proxy_port }}"
    http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "{{ proxy_host }}:{{ proxy_port }}"
- name: install hdfs (head node)
  hosts: namenode
  gather_facts: false
  become: true
  roles: 
  - name_node 
- name: install hdfs (data node)
  hosts: datanodes
  gather_facts: false
  become: true
  roles: 
  - data_node 
- name: yarn proxy installed 
  hosts: yarn_edge
  gather_facts: false
  become: true
  roles: 
  - yarn_edge 
- name: install yarn (resource manager nodes)
  hosts: resourcemanager
  gather_facts: false
  become: true
  roles: 
  - resource_manager 
- name: install yarn (node manager)
  hosts: nodemanagers
  gather_facts: false
  become: true
  roles: 
  - node_manager 
- name: install spark (gateway node)
  hosts: spark_edge
  gather_facts: false
  become: true
  roles: [spark_edge]
  environment:
    TMPDIR: "{{ tmp_dir }}"
    HTTPS_PROXY: "http://{{ proxy_host }}:{{ proxy_port }}"
    HTTP_PROXY: "http://{{ proxy_host }}:{{ proxy_port }}"
    http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "{{ proxy_host }}:{{ proxy_port }}"
- name: install spark shuffle service on yarn
  hosts: nodemanagers
  gather_facts: false
  become: true
  roles: [spark_shuffle]
- name: install httpfs (gateway node)
  hosts: hdfs_edge
  gather_facts: false
  become: true
  roles: [hdfs_edge]
  environment:
    http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "{{ proxy_host }}:{{ proxy_port }}"
- name: install airflow
  hosts: orchestrator
  gather_facts: false
  become: true
  roles: [airflow]
  environment:
    TMPDIR: "{{ tmp_dir }}"
    HTTPS_PROXY: "http://{{ proxy_host }}:{{ proxy_port }}"
    HTTP_PROXY: "http://{{ proxy_host }}:{{ proxy_port }}"
    http_proxy: "{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "{{ proxy_host }}:{{ proxy_port }}"
- name: finalize upgrade
  hosts: namenode
  gather_facts: false
  become: true
  roles:
  - finalize_upgrade_namenode
- name: decomission datanodes
  hosts: namenode
  gather_facts: false
  become: true
  roles:
  - decomission_datanodes
- name: add datanodes
  hosts: namenode
  gather_facts: false
  become: true
  roles:
  - add_datanodes
