---
- name: hadoop group present workers
  group:
    name: hadoop
  tags : create_users
- name: users present 
  tags : create_users 
  user: 
    name: "{{ item.name }}"
    group: hadoop
    groups: ssh
  with_items: "{{ hostvars[groups['namenode'][0]].created_users.results }}"
  when: hostvars[groups['namenode'][0]].created_users is defined
  loop_control:
    label: "{{ item.name }}"
- name: collecte keys to register 
  tags: [create_users]
  shell: |
    echo {{item[1]}}
    cat /home/{{ item[1] }}/.ssh/id_rsa.pub
  delegate_to: "{{ item[0] }}"
  with_nested: 
  - "{{ groups.namenode|union(groups.spark_edge) }}"
  - "{{ hadoopusers_ssh }}"
  changed_when: false
  register: out
  check_mode: no
- name: extracting public keys from output
  tags: [create_users]
  set_fact:
    public_keys: "{{ out.results | map(attribute='stdout_lines') | list}}"
- name: authorized keys present
  tags: [create_users]
  authorized_key:
    user: "{{ item[0] }}"
    state: present
    key: "{{ item[1] }}"     
  loop: "{{ public_keys  }}"
