---
- name: yarn proxy service installed
  tags: yarn_up
  template:
    src: templates/yarn-proxyserver.service.j2
    dest: /lib/systemd/system/yarn-proxyserver.service
    owner: root
    group: root
  register: out
- name: reload systemctl if needed
  tags: yarn_up
  command: systemctl daemon-reload
  when: out.changed
- name: proxy server is running
  tags: yarn_up
  service:
    name: yarn-proxyserver
    state: started
- name: update requirement files for yarn (dask)
  tags: [packages, upgrade, python, dask]
  copy:
    dest: "{{ custom_libs }}/pip_yarn_requirements"
    content: |
      dask
      distributed
      dask-yarn
      venv-pack
- name: install python packages for yarn
  tags: [packages, upgrade, python, dask]
  pip:
    requirements: "{{ custom_libs }}/pip_yarn_requirements"
    executable: "{{ pip }}"
  environment:
    TMPDIR: "{{ tmp_dir }}"
    HTTPS_PROXY: "http://{{ proxy_host }}:{{ proxy_port }}"
    HTTP_PROXY: "http://{{ proxy_host }}:{{ proxy_port }}"
