---
- name: authorized keys present
  tags: [ssh4admins, create_users]
  authorized_key:
    user: "{{ item.1 }}"
    state: present
    key: "{{ item.0 }}"     
  loop: "{{ admins | product(hadoopusers)|list }}"
